[BUGFIX] Make Toolbox render again
kitodo/kitodo-presentation pull request #1024
Opened 2023-09-27 15:44 UTC by frank-ulrich-weber

$this->settings['tool'] does not exist, insted there is $this->settings['tools'] with a comma seperated list of tools that cannot be passed to switch directly

2023-09-27 16:26 UTC, beatrycze-volk commented
I'm not sure in which way you are testing that you have this settings not renamed but maybe this change is missing for you (https://github.com/slub/dfg-viewer/pull/235). Configurations for toolbox are placed in kitodo-presentation and dfg-viewer.

2023-09-28 08:24 UTC, frank-ulrich-weber commented
ok, maybe I understood something wrong here. I added the Toolbox Plugin, the Toolbox Default Templates and than select the required tools within the Toolbox Plugin Setup. No Tools are displayed with that setup. Then I stepped through renderTools() method and realised that there is no $this->settings['tool'], but instead $this->settings['tools'] with a comma seperated list of the selected tools and thought this must be a bug. Where is my mistake in thinking?

2023-10-23 08:27 UTC, sebastian-meyer commented
I think there is a misunderstanding about how the toolbox is supposed to work. The original idea was, that you can add the toolbox to your site once and it then can contain multiple tools. That's why we had a comma-separated list of tools which where all rendered inside one toolbox.
As far as I understand, the changes from @beatrycze-volk for the DFG-Viewer are now using multiple instances of toolboxes, each containing a single tool.

I suggest restoring the old behavior, because that wouldn't break current installations and gives more flexibility (as you can add one toolbox with multiple tools as well as several toolboxes with one tool each).

@beatrycze-volk and @frank-ulrich-weber: What do you think?

2023-10-23 11:18 UTC, beatrycze-volk commented
> As far as I understand, the changes from @beatrycze-volk for the DFG-Viewer are now using multiple instances of toolboxes, each containing a single tool.
> 
> I suggest restoring the old behavior, because that wouldn't break current installations and gives more flexibility (as you can add one toolbox with multiple tools as well as several toolboxes with one tool each).
> 
> @beatrycze-volk and @frank-ulrich-weber: What do you think?

But I didn't change configuration for tools, only renamed it... I was not reimplementing the logic, only refactored methods and renamed configuration. The split onto separated tools in configuration needed to happen earlier.

2023-10-23 12:19 UTC, sebastian-meyer commented
OK, if the functionality is unchanged, we should revert to `tools` instead of `tool` for the settings, because it can in fact be a comma-separated list of multiple tools.

2023-10-24 14:35 UTC, sebastian-meyer commented
So, I'll merge this for Kitodo.Presentation. @beatrycze-volk Do you revert changes for the DFG-Viewer accordingly?

2023-10-24 14:39 UTC, sebastian-meyer requested changes

2023-10-24 14:39 UTC, sebastian-meyer commented on Classes/Controller/ToolboxController.php
> +            {
```suggestion
            foreach($tools as $tool) {
```

2023-10-24 14:40 UTC, sebastian-meyer requested changes

2023-10-24 14:40 UTC, sebastian-meyer commented on Classes/Controller/ToolboxController.php
> +            foreach($tools as $tool) {
```suggestion
            foreach ($tools as $tool) {
```

2023-10-24 14:41 UTC, sebastian-meyer approved these changes

2023-10-24 14:51 UTC, merged