Revert changes on `errorAction` to fix #1082
kitodo/kitodo-presentation pull request #1111
Opened 2023-12-07 08:40 UTC by csidirop

Fix for #1082

2023-12-07 11:22 UTC, beatrycze-volk commented
Please add comment that this change is made to keep it compatible with TYPO3 10, but in the moment of migration to TYPO3 11 this change must be again reverted (as explained here https://github.com/kitodo/kitodo-presentation/pull/1091)

2023-12-16 12:39 UTC, sebastian-meyer requested changes

2023-12-16 12:39 UTC, sebastian-meyer commented on Classes/Controller/Backend/NewTenantController.php
> +        // (this change is made to keep it compatible with TYPO3 10)
```suggestion
        // TODO: Call parent::errorAction() when dropping support for TYPO3 v10.
```

2023-12-16 12:39 UTC, sebastian-meyer approved these changes

2023-12-16 12:43 UTC, merged