[FEATURE] Make ALTO parser register namespaces individually
kitodo/kitodo-presentation pull request #1117
Opened 2023-12-21 08:01 UTC by michaelkubina

This PR makes the ALTO Parser agnostic of the actual ALTO schema version in the provided file. It checks the document namespaces and registers it accordingly. This way we can index ALTO files in the schema versions 2, 3 and 4.

I have testet it in our development enviroment with SOLR 9.4.0 and the ocr-highlighting module in version 0.8.3. I have not encountered any issues here. It has been rolled out in our productive enviroment as well.

While it does not resolve the general namespace issue, it does at least resolve the ALTO issue.

This is related to #488 .

2024-05-16 07:56 UTC, csidirop commented
I would suggest adding a feedback for future "unsupported" versions. This could be a log entry or writing direct to the command line (via the SymfonyStyle). This way at least we know that there is something off.

Proposal: Add an `else`-block which catches all other cases and handle some form feedback.

2024-05-16 08:11 UTC, csidirop requested changes

2024-05-16 08:11 UTC, csidirop commented on Classes/Format/Alto.php
> +
```suggestion
        if (in_array('http://www.loc.gov/standards/alto/ns-v2#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v2#');
        } elseif (in_array('http://www.loc.gov/standards/alto/ns-v3#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v3#');
        } elseif (in_array('http://www.loc.gov/standards/alto/ns-v4#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v4#');
        }

```

2024-05-16 08:11 UTC, csidirop commented on Classes/Format/Alto.php
> +        }
```suggestion
        if (in_array('http://www.loc.gov/standards/alto/ns-v2#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v2#');
        } elseif (in_array('http://www.loc.gov/standards/alto/ns-v3#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v3#');
        } elseif (in_array('http://www.loc.gov/standards/alto/ns-v4#', $namespace, true)) {
            $xml->registerXPathNamespace('alto', 'http://www.loc.gov/standards/alto/ns-v4#');
        }
```

2024-05-16 11:24 UTC, stweil commented on Classes/Format/Alto.php
> +
```suggestion

```

2024-05-16 11:33 UTC, stweil commented on Classes/Format/Alto.php
> +        }
What about adding a private function which registers the namespace and avoids the duplication of code?

2024-05-16 13:00 UTC, BFallert commented
I have testet it in our development enviroment with SOLR 8.11.2.
I have tested documents with ALTO 2.x / 3.x / 4.x.

2024-05-17 07:04 UTC, michaelkubina commented
as proposed by @stweil i have moved the namespace registration to a private function to reduce code duplication.

...

> I would suggest adding a feedback for future "unsupported" versions. This could be a log entry or writing direct to the command line (via the SymfonyStyle). This way at least we know that there is something off.

> Proposal: Add an else-block which catches all other cases and handle some form of feedback.

while i like this idea, i currently have no time to look into the depths of how to achieve this. but we should keep that in mind for the future. looking at what ocr engines output currently, we cover the necessary schemas

2024-05-17 08:07 UTC, stweil approved these changes
Thanks!

2024-05-21 06:58 UTC, sebastian-meyer approved these changes

2024-05-21 06:59 UTC, merged