Scheduler tasks for indexing, reindexing and harvesting of documents
kitodo/kitodo-presentation pull request #1119
Opened 2024-01-09 10:07 UTC by frank-ulrich-weber

Pres_01-2023_Solr-Verbesserungen:
A task for optimizing the index will be added when this is merged.

2024-05-24 07:48 UTC, sebastian-meyer commented
Could you please fix the PHPStan and Codacy issues?
Also, I think you need to add `typo3/cms-scheduler` to `composer.json` in order for this to work.

2024-06-14 08:41 UTC, frank-ulrich-weber commented
At the moment I don't know how to resolve the remaining issues. The PHPStan and the first two Codays issues are correct but specified by the method signature of the scheduler interface. Additionaly I have no idear how to prevent the Cyclomatic Complexity of validateAdditionalFields() in a sensible way. Any hints? Thanks.

2024-07-05 12:04 UTC, sebastian-meyer requested changes

2024-07-05 12:04 UTC, sebastian-meyer commented on Classes/Command/IndexCommand.php
> +                return 1;
```suggestion
                return BaseCommand::FAILURE;
```

2024-07-05 12:04 UTC, sebastian-meyer commented on Classes/Task/BaseAdditionalFieldProvider.php
> +use TYPO3\CMS\Core\Database\Connection;
```suggestion
use Kitodo\Dlf\Common\Helper;
use TYPO3\CMS\Backend\Tree\Repository\PageTreeRepository;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Messaging\FlashMessage;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Scheduler\AdditionalFieldProviderInterface;
use TYPO3\CMS\Scheduler\Controller\SchedulerModuleController;
```
Please import namespaces in alphabetical order for better readibility.

2024-07-05 12:04 UTC, sebastian-meyer commented on Classes/Task/BaseAdditionalFieldProvider.php
> +    public function saveAdditionalFields(array $submittedData, AbstractTask $task)
```suggestion
    public function saveAdditionalFields(array $submittedData, BaseTask $task)
```
PHPStan correctly mentions all the calls to undefined methods in this method. That's because you declare `$task` as being of type `AbstractTask`, but then call methods which are only defined in `BaseTask`. I think declaring `$task` as being of type `BaseTask` should fix this. (On the other hand this may break the interface compatibility...)

2024-07-10 13:27 UTC, sebastian-meyer commented on Classes/Task/BaseAdditionalFieldProvider.php
> +    public function saveAdditionalFields(array $submittedData, AbstractTask $task)
Alternatively, you can add a comment for PHPStan that clarifies the type of `$task` as being `BaseTask`. The comment should be placed directly above the first usage of `$task`:
```php
/* @var BaseTask $task */
```

2024-07-16 06:47 UTC, sebastian-meyer requested changes
Hier ein Vorschlag, um das `AbstractTask`/`BaseTask`-Problem hoffentlich zu lösen.

2024-07-16 06:47 UTC, sebastian-meyer commented on Classes/Task/BaseAdditionalFieldProvider.php
> +    }
```suggestion
    /**
     * Saves additional fields for a task
     *
     * @param array $submittedData The data fields to add to the task
     * @param BaseTask $task The task the data should be added to
     *
     * @return void
     */
    public function saveAdditionalFields(array $submittedData, AbstractTask $task)
    {
        /** @var BaseTask $task */
        $task->setDryRun(!empty($submittedData['dryRun']));
        if (isset($submittedData['doc'])) {
            $task->setDoc(htmlspecialchars($submittedData['doc']));
        }
        if (isset($submittedData['lib'])) {
            $task->setLib((int) $submittedData['lib']);
        }
        if (isset($submittedData['coll']) && is_array($submittedData['coll'])) {
            $task->setColl($submittedData['coll']);
        } else {
            $task->setColl([]);
        }
        if (isset($submittedData['pid'])) {
            $task->setPid((int) $submittedData['pid']);
        }
        if (isset($submittedData['solr'])) {
            $task->setSolr((int) $submittedData['solr']);
        }
        if (isset($submittedData['owner'])) {
            $task->setOwner(htmlspecialchars($submittedData['owner']));
        }
        $task->setAll(!empty($submittedData['all']));
        if (isset($submittedData['from'])) {
            $task->setFrom(htmlspecialchars($submittedData['from']));
        }
        if (isset($submittedData['until'])) {
            $task->setUntil(htmlspecialchars($submittedData['until']));
        }
        if (isset($submittedData['set'])) {
            $task->setSet(htmlspecialchars($submittedData['set']));
        }
    }
```

2024-07-16 09:35 UTC, sebastian-meyer approved these changes
Good work, thank you!

2024-07-16 09:36 UTC, merged