[MAINTENANCE] Use nested extend configuration
kitodo/kitodo-presentation pull request #1150
Opened 2024-01-29 13:59 UTC by beatrycze-volk

Over the time the configuration has grown quite significantly so introduction of nested configuration increases the readability.

2024-01-30 11:26 UTC, beatrycze-volk commented
I would assume that it is no the error here:
```
Tests/Functional/FunctionalTestCase.php#L127
The use of function getenv() is discouraged
```

2024-05-22 15:37 UTC, beatrycze-volk commented
Codacy warning about getevn() should be solved by #1206

2024-05-28 13:44 UTC, sebastian-meyer requested changes

2024-05-28 13:44 UTC, sebastian-meyer commented on ext_conf_template.txt
> +general.useExternalApisForMetadata = 0
```suggestion
# cat=General; type=string; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.userAgent
general.userAgent = Kitodo.Presentation
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.forceAbsoluteUrl
general.forceAbsoluteUrl = 0
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.forceAbsoluteUrlHttps
general.forceAbsoluteUrlHttps = 0
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.caching
general.caching = 0
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.publishNewCollections
general.publishNewCollections = 1
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.unhideOnIndex
general.unhideOnIndex = 0
# cat=General; type=boolean; label=LLL:EXT:dlf/Resources/Private/Language/locallang_labels.xlf:config.general.useExternalApisForMetadata
general.useExternalApisForMetadata = 0
```

2024-05-28 13:46 UTC, sebastian-meyer approved these changes

2024-05-29 06:49 UTC, merged

2024-06-25 17:01 UTC, fschoelzel commented
Found missing nesting key for `metadataFormats` in `Resources/Private/Language/locallang_labels.xlf`
See pull Request: #1264