[FEATURE] Implement document validation before document is saved to SOLR
kitodo/kitodo-presentation pull request #1158
Opened 2024-01-31 16:45 UTC by beatrycze-volk

There exists possibility that during save to database document contains 'record_id', but already during saving to SOLR it doesn't. It is necessary to validate fields in both places to avoid it.

Depends on #1149

2024-05-28 12:53 UTC, beatrycze-volk commented
Documentation build failed:

```
In inline-node.html.twig line 2:
                                                                               
  An exception has been thrown during the rendering of a template ("Failed to  
   connect to docs.typo3.org port 80 after 2010 ms: Couldn't connect to serve  
  r for "http://docs.typo3.org/typo3cms/TyposcriptReference/objects.inv.json"  
  .").                                                                         
                                                                               

In ErrorChunk.php line 56:
                                                                               
  Failed to connect to docs.typo3.org port [80](https://github.com/kitodo/kitodo-presentation/actions/runs/9269551905/job/25500591891?pr=1158#step:3:81) after 2010 ms: Couldn't connect  
   to server for "http://docs.typo3.org/typo3cms/TyposcriptReference/objects.  
  inv.json".                                                                   
                                                                               

In CurlResponse.php line 315:
                                                                               
  Failed to connect to docs.typo3.org port 80 after 2010 ms: Couldn't connect  
   to server for "http://docs.typo3.org/typo3cms/TyposcriptReference/objects.  
  inv.json".
```

2024-05-29 09:42 UTC, sebastian-meyer requested changes
Just a few Codacy issues...

2024-05-29 09:42 UTC, sebastian-meyer commented on Classes/Command/IndexCommand.php
> +                $io->error('ERROR: Document with UID "' . $document->getUid() . '" could not be indexed on PID ' . $this->storagePid . ' . There are missing mandatory fields (at least one of those: '
```suggestion
                $io->error('ERROR: Document with UID "' . $document->getUid() . '" could not be indexed on PID ' . $this->storagePid . ' . There are missing mandatory fields (at least one of those: ' . $this->extConf['requiredMetadataFields'] . ') in this document.');
```

2024-05-29 09:42 UTC, sebastian-meyer commented on Classes/Command/IndexCommand.php
> +            $io->error('ERROR: Document with UID "' . $document->getUid() . '" could not be indexed on Solr core ' . $solrCoreUid . ' . There are missing mandatory fields (at least one of those: ' .
```suggestion
            $io->error('ERROR: Document with UID "' . $document->getUid() . '" could not be indexed on Solr core ' . $solrCoreUid . ' . There are missing mandatory fields (at least one of those: ' . $this->extConf['requiredMetadataFields'] . ') in this document.');
```

2024-05-29 09:43 UTC, sebastian-meyer approved these changes

2024-05-29 09:45 UTC, merged