Add `languageUid` to `index_name` to make it unique
kitodo/kitodo-presentation pull request #1186
Opened 2024-03-07 12:44 UTC by csidirop

Fixes #1182 and the issues described in https://github.com/kitodo/kitodo-presentation/issues/1182#issuecomment-1981079193 .

2024-03-07 15:06 UTC, sebastian-meyer requested changes
I am wondering if we would need to change the default translation method as well. What happens if we manually translate a metadata record in the backend? I assume the translated record would also get an exact copy of the original `index_name` triggering the same issues when moving the newly translated record around...

Maybe we need to work around this by changing the [`l10n_mode`](https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/Columns/Properties/L10nMode.html) from 'exclude' to 'prefixLangTitle' and set [`TCEMAIN.translateToMessage`](https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/PageTsconfig/TceMain.html#pagetcemain-translatetomessage) to an appropriate prefix (like '%s_').

2024-03-07 15:06 UTC, sebastian-meyer commented on Classes/Controller/Backend/NewTenantController.php
> +                    $translatedRecord->setIndexName($indexName."_".$siteLanguage->getLanguageId());
```suggestion
                    $translatedRecord->setIndexName($indexName . '_' . $siteLanguage->getLanguageId());
```

2024-05-07 10:39 UTC, sebastian-meyer commented
@csidirop Could you please verify that this also works for records manually translated in the backend? What does the `index_name` of those records look like?

2024-05-21 07:31 UTC, sebastian-meyer commented
@beatrycze-volk Is this potentially also related to not using the DataHandler in the backend (like in #1184)?

2024-05-21 08:20 UTC, beatrycze-volk commented
> @beatrycze-volk Is this potentially also related to not using the DataHandler in the backend (like in #1184)?

That is quiet possible. With `DataHandler` translated records were created automatically not like now manually.

2024-05-21 08:36 UTC, sebastian-meyer commented
So then this should be fixed with your re-introduction of the DataHandler as mentioned in #1184. Nice!

I'll leave this PR for now, because consistently using the DataHandler would be the better solution.

2024-05-23 10:40 UTC, sebastian-meyer commented
Reverting to using the DataHandler is more work than anticipated. Therefor I'll merge this workaround for now in order to release version 5.0.
I'll open a new issue for DataHandler usage.

2024-05-23 10:42 UTC, sebastian-meyer approved these changes

2024-05-23 10:42 UTC, merged