Fix double entry for pageView plugin configuration
kitodo/kitodo-presentation pull request #1278
Opened 2024-07-18 14:15 UTC by chrizzor

2024-07-18 14:19 UTC, sebastian-meyer requested changes

2024-07-18 14:19 UTC, sebastian-meyer commented on ext_localconf.php
>          \Kitodo\Dlf\Controller\PageViewController::class => 'main',
Müsste die Action dann nicht hier hinzugefügt werden? Denn unter den "non-cacheable actions" taucht sie ja weiterhin auf.

```suggestion
        \Kitodo\Dlf\Controller\PageViewController::class => 'main, addDocument',
```

2024-07-18 14:19 UTC, sebastian-meyer commented on Resources/Private/Partials/Metadata/Entries.html
> +</f:if>
```suggestion
</f:if>

```
Nur eine Kleinigkeit. ;)

2024-07-18 14:27 UTC, sebastian-meyer approved these changes

2024-07-18 14:27 UTC, sebastian-meyer commented
Danke!

2024-07-18 14:28 UTC, merged

2024-07-18 14:35 UTC, sebastian-meyer commented
OK, keine weiteren Exceptions mehr!
Dafür nun aber einige JS-Fehler, sobald man Verovio aktivieren will. Unter anderem scheint an irgendeiner Stelle noch eine Referenz auf `Resources/Public/JavaScript/Midiplayer/wildwebmidi.js` zu stecken, aber die Datei liegt ja jetzt unter `Resources/Public/JavaScript/Verovio/`. (Darum kann ich mich kümmern, es gibt aber noch ein paar andere JS-Fehler in der Konsole, die du dir gerne mal anschauen könntest.)

2024-07-18 14:36 UTC, chrizzor commented
Sehr gut!
Ok, schaue ich mir an!
Komme aber vermutlich erst morgen früh dazu.

2024-07-18 15:07 UTC, sebastian-meyer commented
So, die Fehlermeldung wegen `WildWebMidi` bin ich losgeworden. Da waren noch ein paar falsche Pfadangaben drin. Taktweises Blättern funktioniert damit nun auch, das war wohl ein Seiteneffekt von dem Midi-Fehler. Was aber leider immer noch nicht geht, ist Verovio. Sobald ich da auf den Button zum Aktivieren klicke, macht das Bild zwar Platz, es erscheint in der rechten Spalte aber kein Verovio. Stattdessen schmeißt die `ScoreControl.js` einen Error in der Konsole. Weiß aber nicht, ob das die Ursache für das Nicht-Funktionieren von Verovio ist oder wieder nur ein Nebeneffekt.

Ich bin morgen vormittag unterwegs, schaue aber gerne danach wieder drauf, wenn du nochmal Änderungen vorgenommen hast!

2024-07-19 09:34 UTC, chrizzor commented
Verovio wollte nicht laden, da bei der Karte die Angabe "center" fehlte und das Click-Event der Sync-Buttons hat irgendwie zu Fehlern geführt. Die habe jetzt erstmal auf den vorherigen Stand zurückgesetzt.
Bei mir lokal funktioniert es damit wieder. PR habe ich gestellt.