[FEATURE] Setting for allow write into index
kitodo/kitodo-presentation pull request #1296
Opened 2024-08-09 15:46 UTC by beatrycze-volk

2024-08-14 14:56 UTC, beatrycze-volk commented
```
Issues
======
+ Solved 1
- Added 1
           

Complexity decreasing per file
==============================
+ Classes/Command/ReindexCommand.php  -6
+ Classes/Command/IndexCommand.php  -6
```

So all in all, the end complexity is decreased, but getting it to the expected threshold can be hard here.

2024-08-14 15:38 UTC, sebastian-meyer requested changes

2024-08-14 15:38 UTC, sebastian-meyer commented on Classes/Command/DeleteCommand.php
> +            $io->error('This system is not allowed to write into the SOLR Index.');
```suggestion
            $io->error('This system is not allowed to write to the Solr index.');
```

2024-08-14 15:38 UTC, sebastian-meyer commented on Classes/Command/IndexCommand.php
> +            $io->error('This system is not allowed to write into the SOLR Index.');
```suggestion
            $io->error('This system is not allowed to write to the Solr index.');
```

2024-08-14 15:38 UTC, sebastian-meyer commented on Classes/Command/ReindexCommand.php
> +            $io->error('This system is not allowed to write into the SOLR Index.');
```suggestion
            $io->error('This system is not allowed to write to the Solr index.');
```

2024-08-14 15:38 UTC, sebastian-meyer commented on Resources/Private/Language/de.locallang_labels.xlf
> +                <source>Allow write to the SOLR? (default is "TRUE")</source>
```suggestion
                <target>Schreibzugriff auf Solr-Index? (Standard ist "TRUE")</target>
                <source>Allow write to the Solr index? (default is "TRUE")</source>
```

2024-08-14 15:38 UTC, sebastian-meyer commented on Resources/Private/Language/locallang_labels.xlf
> +				<source>Allow write to the SOLR? (default is "TRUE")</source>
```suggestion
				<source>Allow write to the Solr index? (default is "TRUE")</source>
```

2024-08-14 15:39 UTC, sebastian-meyer approved these changes

2024-08-14 15:43 UTC, sebastian-meyer commented
Don't worry about the Codacy issue! That's fine!

But could you please explain the reasoning behind this feature? Why would you want to have a ready-only Solr index (but not database)? And what about other places where we write to the Solr index (like `Classes\Hooks\DataHandler.php` for example)?

2024-08-14 16:06 UTC, beatrycze-volk commented
> But could you please explain the reasoning behind this feature? Why would you want to have a read-only Solr index (but not database)? And what about other places where we write to the Solr index (like `Classes\Hooks\DataHandler.php` for example)?

I was asked about it by @ByteParty. There are going to be instances of Kitodo.Presentation where calling the indexing commands should not be allowed.

2024-08-14 16:39 UTC, sebastian-meyer commented
I am not sure if we should implement this in Kitodo.

Primarily because doing it right (i. e. preventing writing everywhere we currently interact with Solr) becomes very complicated. We would have to disallow writing in the `DataHandler` as well which essentially means not allowing any field configuration and data changes in the backend (because otherwise we would get inconsistencies between index and database).

But also, because this seems to be a very SLUB-specific issue and it would be much easier to just prevent the Solr update handler from being accessible by Kitodo. This could be done simply by configuration on the Solr side. Or am I missing something?

2024-08-15 06:34 UTC, ByteParty commented
It is only a matter of switching off the indexer cron. It is not about preventing all write operations in the SOLR. The indexer should be on its own TYPO3 instance. So there will be a TYPO3 instance in which editors can edit the data and a TYPO3 instance that keeps the index / DB up to date. Alternatively, the system design of Kitoto Presentation can be reconsidered and the indexer can be outsourced to an extra extension.
The background is the increased performance requirements due to the many AI bots.

2024-08-19 13:50 UTC, sebastian-meyer commented
I still don't understand why you need a new configuration flag to disable the indexer. Just don't use it if you don't want to... Since the indexer is a CLI command, it can't be called "accidentally" by bots.

2024-08-20 06:09 UTC, ByteParty commented
The indexer is not called by bots. The indexer is simply performance hungry. Yes, you could  not call the indexer, that's right. But with the flag, the system architecture is cleanly documented in Git. On the other side, an admin cannot start the indexer by mistake.

2024-08-20 11:59 UTC, sebastian-meyer commented
Closing this after speaking to @ByteParty: In order to make this merge-able more work would be necessary which is not worth it considering the "problem" can be solved organisationally.

2024-08-20 11:59 UTC, closed without merging