Xml validator
kitodo/kitodo-presentation pull request #1313
Opened 2024-08-26 17:07 UTC by markusweigelt

2024-09-09 13:55 UTC, sebastian-meyer requested changes

2024-09-09 13:55 UTC, sebastian-meyer commented on DEVELOPMENT.md
>  ```
Without the removed command this makes no more sense. Was the removal intentional? Then this should be removed as well.

2024-09-23 10:24 UTC, markusweigelt commented
@sebastian-meyer Thanks, I had overlooked that. I added the lines back.

2024-09-23 14:54 UTC, sebastian-meyer approved these changes

2024-09-23 14:55 UTC, merged

2024-09-24 12:48 UTC, thomaslow commented
Hi Sebastian and Markus. Your recent changes fail unit tests in my branch (php 7.4, typo3 v11). Any ideas?

```
There was 1 error:

1) Kitodo\Dlf\Tests\Unit\Validation\SaxonXslToSvrlValidatorTest::testValidation
InvalidArgumentException: Saxon JAR file not found.

/home/runner/work/kitodo-presentation/kitodo-presentation/Classes/Validation/SaxonXslToSvrlValidator.php:47
/home/runner/work/kitodo-presentation/kitodo-presentation/Tests/Unit/Validation/SaxonXslToSvrlValidatorTest.php:67
phpvfscomposer:///home/runner/work/kitodo-presentation/kitodo-presentation/vendor/phpunit/phpunit/phpunit:106
/home/runner/work/kitodo-presentation/kitodo-presentation/vendor/bin/phpunit:118

--

There was 1 failure:

1) Kitodo\Dlf\Tests\Unit\Validation\SaxonXslToSvrlValidatorTest::testXslFileNotFound
Failed asserting that exception message 'Saxon JAR file not found.' contains 'XSL Schematron file not found.'.

phpvfscomposer:///home/runner/work/kitodo-presentation/kitodo-presentation/vendor/phpunit/phpunit/phpunit:106
/home/runner/work/kitodo-presentation/kitodo-presentation/vendor/bin/phpunit:118
```

2024-09-24 15:01 UTC, markusweigelt commented
@thomaslow The problem seem to be the Typo3 function `GeneralUtility::getFileAbsFileName` https://github.com/thomaslow/kitodo-presentation/blob/6363217ab3c7c0a1863e45dfe75de2ebe16b7949/Classes/Validation/SaxonXslToSvrlValidator.php#L43, cause with extension path `EXT:dlf/Tests/Fixtures/Format/alto.xml` parameter the resolved path is not returned when running with the updated `typo3/testing-framework`. The behavior of resolving extension paths may have changed in the new version.

2024-09-24 15:45 UTC, markusweigelt commented
@thomaslow i run the tests again with `typo3/testing-framework` 6.16.9, which succeeds, and with 7.1.0 I can reproduce the problem. I'll take a look at it tomorrow when I get a chance.

2024-09-24 17:25 UTC, thomaslow commented
@markusweigelt I followed to empty result of `GeneralUtility::getFileAbsFileName` to the Typo3 [PackageManager->getActivePackages()](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Package/PackageManager.php#L621). It seems the package key `EXT:dlf` can not be resolved, because the package is not known at all when running the unit test. 

The difference between `testing-framework` v6 and v7 seems to be in the [UnitTestsBootstrap.php](https://github.com/TYPO3/testing-framework/compare/6...7#diff-1557a22f50b51bb776e57ff5f503802e3e5a668dab6f590c9b5236e016a9291a). They set `composerMode = true`, which prevents the [PackageManager](https://github.com/TYPO3/typo3/blob/2126407004b2dec61a14dd0059655f43f185a00a/typo3/sysext/core/Classes/Package/PackageManager.php#L247C1-L247C2) from scanning for extensions. Removing this check for composer mode loads all package paths including `dlf` and the unit test works.

I'm not sure how to fix this. I see two options:
- not use `GeneralUtility::getFileAbsFileName` with an extension key in unit tests, e.g., specify only absolute file paths
- move tests to functional tests, which have a different bootstrap process

2024-09-25 06:46 UTC, sebastian-meyer commented
We copied `Build/Test/runTests.sh` a while ago from TYPO3, maybe we need to update this script in order to correctly run the tests in `composerMode`? The script seems really old anyways, referencing a lot of outdated versions (i. e. for MySQL) and missing current versions (like PHP 8.3).

2024-09-25 06:51 UTC, sebastian-meyer commented
I opened a new issue in order to discuss this further: #1348