Fix some typos in configuration, documentation and code comments
kitodo/kitodo-presentation pull request #1360
Opened 2024-10-17 15:54 UTC by stweil

Most of them were found using `codespell` and `typos`.

2024-10-17 15:55 UTC, stweil commented on Classes/Common/MetsDocument.php
> +            // Get track info with begin end extent time for later assignment with musical
I am not sure here. Perhaps "and extent time" was intended.

2024-10-21 15:25 UTC, sebastian-meyer requested changes

2024-10-21 15:25 UTC, sebastian-meyer commented on Classes/Common/MetsDocument.php
> +            // Get track info with begin end extent time for later assignment with musical
Yes, it should be "and" instead of "end".
```suggestion
            // Get track info with begin and extent time for later assignment with musical
```

2024-10-21 15:25 UTC, sebastian-meyer approved these changes

2024-10-21 15:49 UTC, merged