[MAINTENANCE] Change log level to INFO
kitodo/kitodo-presentation pull request #1376
Opened 2024-11-18 09:50 UTC by markusweigelt

Using default should not be a warning because it signals a problem and distracts from actual issues.

The following warning will be shown in the log.
```
Setting "displayIiifDescription" not set, using default value "1". Probably FlexForm for controller "Kitodo\Dlf\Controller\MetadataController" is not read. 
```
I think it's useful to inform about configuration decisions without signaling a problem. I'll adjust the message accordingly.

2024-11-21 09:00 UTC, beatrycze-volk commented
Actually it is a real problem, as FlexForm should be configured and used.

2024-11-21 09:21 UTC, markusweigelt commented
> Actually it is a real problem, as FlexForm should be configured and used.

I think then there is no need for default values here but an error message that this FlexForm must be configured.

2024-11-21 09:23 UTC, beatrycze-volk commented
> > Actually it is a real problem, as FlexForm should be configured and used.
> 
> I think then there is no need for default values here but an error message that this FlexForm must be configured.

But then without those values the whole page crashes.

2024-12-16 18:11 UTC, sebastian-meyer commented
I am with @markusweigelt here: Falling back to default values should not be considered an error. If it was we shouldn't provide default values, but immediately throw an exception when mandatory settings are not available.

2024-12-16 18:15 UTC, sebastian-meyer commented
Making sure that Flexform settings are read at all (if provided) is a different issue which should not be adressed by warning about the usage of default values. Also, I think not using Flexform at all, but instead providing settings in Typoscript is perfectly fine.

So, in essence: The plugins should make sure that mandatory settings are provided (and throw an error otherwise), but they should not need to worry about where those settings come from (Flexform, Typoscript, Extension config).

2024-12-16 18:16 UTC, sebastian-meyer requested changes

2024-12-16 18:16 UTC, sebastian-meyer commented on Classes/Controller/AbstractController.php
> +            $this->logger->info('Setting "' . $setting . '" not set, using default value "' . $value . ' in "' . get_class($this) . '".');
```suggestion
            $this->logger->info('Setting "' . $setting . '" not set, using default value "' . $value . '" in ' . get_class($this) . '.');
```

2024-12-16 18:17 UTC, sebastian-meyer approved these changes

2024-12-16 18:21 UTC, merged