[FEATURE] Seamless document browsing
kitodo/kitodo-presentation pull request #1380
Opened 2024-11-21 10:51 UTC by michaelkubina

This PR adds a feature to the navigation controller, that allows navigating to the prev/next document (volume/issue/etc) relative to the currently one viewed. It implements backtracking, so that it allows for overflowing to the next leafe node if necesseary, e.g. from the last newspaper issue of the current year to the first issue of the next year (and back). Since the backtracking is recursive, this allows backtracking any depths which will very well be necessary for complex document trees from Kalliope (inventories with subinventories with subinventories etc.).

This addresses the following issue: #760

2025-01-22 16:18 UTC, beatrycze-volk requested changes

2025-01-22 16:18 UTC, beatrycze-volk commented on Classes/Domain/Repository/DocumentRepository.php
> +        $parentId = $currentDocument->getPartof();
This change will only work in case when documents are stored in database, but in case of DFG Viewer they are passed as XML files. It causes error:
`Call to a member function getPartof() on null`

It is necessary to make a null check already on `$currentDocument` variable.

2025-02-01 00:23 UTC, sebastian-meyer requested changes

2025-02-01 00:23 UTC, sebastian-meyer commented on Classes/Domain/Repository/DocumentRepository.php
> +        $parentId = $currentDocument->getPartof();
@michaelkubina Please apply your fix from #1381 for this pull request as well.

2025-02-03 09:57 UTC, sebastian-meyer approved these changes
Thank you!

2025-02-03 09:58 UTC, merged