[FEATURE] 3D viewer selection
kitodo/kitodo-presentation pull request #1395
Opened 2024-12-04 13:41 UTC by markusweigelt

- Adjusts the `modeldownloadtool` to additionally retrieve the model url from the `tx_dlf[model]` parameter.
- It provides the `viewerselectiontool` to display all viewers that support the model format for rendering (therefore, the model URL is extracted from the METS file or the model parameter is used).

![image](https://github.com/user-attachments/assets/ecc5087b-7020-402a-b5f9-6eea5cc0cad6)

- documentation of both tools

2024-12-16 20:58 UTC, sebastian-meyer requested changes

2024-12-16 20:58 UTC, sebastian-meyer commented on Classes/Controller/ToolboxController.php
> +        if ($modelUrl) {
Shouldn't this check for NO `$modelUrl` instead?

```suggestion
        if ($modelUrl === '') {
```

2025-01-10 10:31 UTC, markusweigelt commented on Classes/Controller/ToolboxController.php
> +        if ($modelUrl) {
Great thx!

2025-01-22 16:48 UTC, beatrycze-volk requested changes

2025-01-22 16:48 UTC, beatrycze-volk commented on Documentation/Plugins/Index.rst
> + - :Property:
Why do you set up this property here?

`fileGrps...` config is configured in `ext_conf_template.txt` (https://github.com/kitodo/kitodo-presentation/blob/4b3a130ff4794170b0fb4fe1970c3f996309b2df/ext_conf_template.txt#L22)

Please move it there.

2025-01-22 16:48 UTC, beatrycze-volk commented on Documentation/Plugins/Index.rst
> +       fileGrpsModelDownload
The same as above.

2025-01-22 16:48 UTC, beatrycze-volk commented on Classes/Controller/ToolboxController.php
> +        } elseif (!($this->isDocMissingOrEmpty() || empty($this->settings['fileGrpsModelDownload']))) {
Access to properties from `ext_conf_template.txt`:
Example: `GeneralUtility::trimExplode(',', $this->extConf['files']['fileGrpThumbs']);`

2025-02-17 13:17 UTC, sebastian-meyer commented
Any news on this one, @markusweigelt?
I'd love to merge this as soon as you fixed the small issues mentioned by @beatrycze-volk.

2025-02-17 13:49 UTC, markusweigelt commented
@sebastian-meyer Currently i had no time to add these changes and so test. I will tackle this soon.

2025-02-17 13:54 UTC, sebastian-meyer commented
Thanks for the head's up!

2025-02-21 14:23 UTC, markusweigelt commented on Classes/Controller/ToolboxController.php
> +        } elseif (!($this->isDocMissingOrEmpty() || empty($this->settings['fileGrpsModelDownload']))) {
Thx for this! I adjusted my implementation accordingly, removed some misleading comments, and eliminated `fileGrpsImageDownload` from `tx_dlf_pdfdownloadtool`

2025-02-26 14:02 UTC, sebastian-meyer submitted a review, later dismissed

2025-02-26 14:17 UTC, sebastian-meyer commented
Shall I wait for your review, @beatrycze-volk?

2025-02-26 15:07 UTC, beatrycze-volk approved these changes

2025-02-26 15:07 UTC, beatrycze-volk commented on Classes/Controller/ToolboxController.php
> +                $file = $this->getFile($this->requestData['page'], GeneralUtility::trimExplode(',', $this->extConf['files']['useGroupsModel']));
It would be nice to use consistently  `$this->useGroupsConfiguration`. so for this case it would be something like `$this->useGroupsConfiguration->getModel()`. 

The function for it should be implemented inside `UseGroupsConfiguration` and look like this

```
    public function getModel(): array
    {
        return $this->getByType('Model');
    }
```

But for now you can leave it as it is.

2025-02-27 13:58 UTC, markusweigelt commented on Classes/Controller/ToolboxController.php
> +                $file = $this->getFile($this->requestData['page'], GeneralUtility::trimExplode(',', $this->extConf['files']['useGroupsModel']));
Now adjusted as you suggested.

2025-02-27 15:18 UTC, beatrycze-volk approved these changes
Thanks!

2025-02-28 07:59 UTC, sebastian-meyer approved these changes

2025-02-28 08:00 UTC, merged