[BUGFIX] MIME Type Filter
kitodo/kitodo-presentation pull request #1419
Opened 2024-12-30 16:17 UTC by fschoelzel

Fix Mime Type Filter using File Extension instead of mimetype description out of METS/MODS.
Because of inconsitent use of MIME Type description in mets file section.

2025-01-22 17:14 UTC, beatrycze-volk requested changes

2025-01-22 17:14 UTC, beatrycze-volk commented on Classes/Common/Helper.php
> +            $fileExtension = pathinfo($fileUrl, PATHINFO_EXTENSION);
Maybe using https://api.typo3.org/11.5/classes/TYPO3-CMS-Core-Utility-PathUtility.html would remove Codacy error.

2025-02-01 00:52 UTC, sebastian-meyer commented
Technically this is fine, but I am not sure if it's a good idea to allow invalid MIME types (by ignoring them). People should better fix their METS files instead...
Also, image servers like Cantaloupe don't necessarily provide file extensions, because the file type can be specified by parameter. So some image server links won't have file extensions at all while others may have misleading extension (like "jp2", although the actual graphic is png-encoded).

Are invalid MIME types a common problem in METS files? Otherwise I'd prefer asking the "Bibliothek der Friedrich-Ebert-Stiftung" to fix their files.

2025-02-17 13:18 UTC, sebastian-meyer commented
Any news on this, @fschoelzel?

2025-02-19 11:59 UTC, fschoelzel commented
> Technically this is fine, but I am not sure if it's a good idea to allow invalid MIME types (by ignoring them). People should better fix their METS files instead... Also, image servers like Cantaloupe don't necessarily provide file extensions, because the file type can be specified by parameter. So some image server links won't have file extensions at all while others may have misleading extension (like "jp2", although the actual graphic is png-encoded).
> 
> Are invalid MIME types a common problem in METS files? Otherwise I'd prefer asking the "Bibliothek der Friedrich-Ebert-Stiftung" to fix their files.

As of my short research, the `<mets:file ID="xxx" MIMETYPE="image/jpg">` is very often.
Thanks for the hints, i didn't thought of this cases. I will change it back to check for the MIMETYPE out of the METS Files.
And, because it is very often, add a exception for `image/jpg` and hope for correct METS Files in the Future.

What do you think @sebastian-meyer ?

2025-02-19 12:06 UTC, sebastian-meyer commented
Yes, that's reasonable! Thank you very much!

2025-02-26 14:13 UTC, sebastian-meyer approved these changes

2025-02-26 14:13 UTC, sebastian-meyer commented
Thank you!

2025-02-26 14:16 UTC, merged