Jump2logicalPage
kitodo/kitodo-presentation pull request #232
Opened 2017-11-21 11:20 UTC by frank-ulrich-weber

2017-11-27 11:28 UTC, sebastian-meyer commented
Could you please describe what this feature is supposed to do? :)

2017-12-01 08:49 UTC, frank-ulrich-weber commented
Sure! Sorry! :-) I don't skip writing an issue the next time.
The land registry offices need a functionality to enter the logical page number. If they do a search, they know the document and the logical page number. The search results in exactly (approximately 90% :-) one search result. They don't want to do a click on the document within the list view and again for the page within the page view. They would like to do a search and as a reault the page view opens imediately on the needed logical page.

2017-12-20 09:38 UTC, sebastian-meyer requested changes
Please check my comment below.

2017-12-20 09:38 UTC, sebastian-meyer commented on dlf/plugins/search/class.tx_dlf_search.php
> +
This seems to be wrong. All of the parameters are set to `uid`?

2017-12-20 12:55 UTC, sebastian-meyer approved these changes

2017-12-20 12:55 UTC, merged