Add Solr queries to collection plugin
kitodo/kitodo-presentation pull request #268
Opened 2018-02-15 15:24 UTC by Erikmitk

This pull request adds Solr queries to the collection plugin. Since #261 allows to define virtual collections via a Solr query those collections should be able to be shown in the collection plugin.

To be able to query the Solr an additional field for selecting a Solr core has been added to the plugin configuration.

I cleaned up some code and replaced several database queries for the corresponding Solr queries to get the necessary data.

**CollectionList**
1. fetch information about selected collections from database
2. for each collection
-- query titles and volumes info from Solr
-- generate output

**SingleCollection**
1. fetch collection information from DB
2. fetch corresponding document UIDs from Solr
3. fetch info from those documents from DB
4. generate output

Step 3 could be eliminated. But we would have to make additional changes. This particular query contains the database field metadata_sorting. That field includes all information for sorting the list view if I got that right. I haven’t figured out how the sorting actually works so that might be wrong.

![image](https://user-images.githubusercontent.com/180686/36263188-ea502f08-1269-11e8-88ea-337c30de5bec.png)

We could probably fetch the values for sorting the documents from the index, but with the options in the selector we would have to add `author` and `year` to the Solr schema. At the moment they are only dynamic fields.

2018-04-17 15:55 UTC, sebastian-meyer requested changes
There are some inconsistencies and errors, please check my inline comments. And please have a look at manually created collections to avoid running into the same bug as with the OAI plugin.

2018-04-17 15:55 UTC, sebastian-meyer commented on plugins/collection/class.tx_dlf_collection.php
> -                $additionalWhere .= ' AND NOT tx_dlf_collections.fe_cruser_id=0';
Your simplification misses this case ($this->conf['show_userdefined'] > 0 && empty($GLOBALS['TSFE']->fe_user->user['uid']). This case is important, because it is used to show all userdefined collections.

2018-04-17 15:55 UTC, sebastian-meyer commented on plugins/collection/flexform.xml
> +							<label>LLL:EXT:dlf/plugins/oai/locallang.xml:tt_content.pi_flexform.solrcore</label>
This is the flexform for the collection plugin, but you are referencing the language file of the oai plugin. Please try to avoid cross-plugin dependencies!

2018-04-17 15:55 UTC, sebastian-meyer commented on plugins/collection/flexform.xml
> +								<minitems>0</minitems>
I am not sure, but shouldn't this be a mandatory field (i.e. minitems=1)?

2018-04-17 15:55 UTC, sebastian-meyer commented on plugins/collection/class.tx_dlf_collection.php
> -
Please preserve those empty lines throughout the file (there are many occasions where you removed them).

2018-04-17 15:55 UTC, sebastian-meyer commented on plugins/collection/class.tx_dlf_collection.php
> +            // All titles except those that are part of something
You confused titles and volumes here. Titles are all documents which do not have an ancestor (i.e. partof == 0), but volumes are all documents which either have an ancestor (i.e. partof != 0) or no descendant (i.e. no other documents exist with descendant.partof == ancestor.uid).
The way you calculate titles and volumes always results in less volumes than titles, but in reality that can never be the case. The number of volumes must be at least as big as the number of titles, almost always it is even bigger.

2018-06-18 11:27 UTC, Erikmitk commented
I am gonna open up a new request for this, because there were a lot of changes in the mean time and I had to rebase my branch. This PR would be quite confusing.

2018-06-18 11:27 UTC, closed without merging