Implementation of enhancement #296 "Refactoring of the listview plugin"
kitodo/kitodo-presentation pull request #312
Opened 2018-11-19 16:39 UTC by frank-ulrich-weber

2018-12-03 08:40 UTC, frank-ulrich-weber commented
Is there a chance for a timely review of this pull request? Thanks!

2018-12-03 10:54 UTC, sebastian-meyer commented
I already started a review two weeks ago and I'm almost done with it. As you can see I also made some changes.
The last concern I am currently investigating is that you moved a lot of search functionality from tx_dlf_solr to tx_dlf_listview. I am not yet sure, if that is a good idea.

2018-12-03 11:00 UTC, frank-ulrich-weber commented
Thank you for your fast reply. I will wait for the result of your review.

2018-12-04 15:34 UTC, sebastian-meyer requested changes

2018-12-04 15:34 UTC, sebastian-meyer commented on common/class.tx_dlf_list.php
> +                    $params['rows'] = 1000000000;
What's the point in having a hard limit if we don't enforce it here?
The default limit should be high enough to avoid running into problems, but it should still be reasonably low to prevent stalling the system. So instead of removing the limit here we should increase the default value if it's necessary.

2018-12-04 15:34 UTC, sebastian-meyer commented on common/class.tx_dlf_list.php
> +                        $params['filterquery'][$key] = array ('query' => $value['query'].' OR toplevel:true');
Shouldn't this be something like
```suggestion
                        $params['filterquery'][$key]['query'] = $value['query'].' OR toplevel:true';
```
to avoid deleting other array keys besides 'query'?

2018-12-06 08:41 UTC, frank-ulrich-weber commented on common/class.tx_dlf_list.php
> +                    $params['rows'] = 1000000000;
Ok, then I think it would be a good idea to configure the limit within the Solr configuration of the extension. What do you think?

2018-12-06 08:53 UTC, frank-ulrich-weber commented on common/class.tx_dlf_list.php
> +                        $params['filterquery'][$key] = array ('query' => $value['query'].' OR toplevel:true');
I think we can savely change this. At the moment we don't use any other array keys besides query, but it increases the flexibility for future changes. I think we should change a second occurrence, too.  [tx_dlf_solr](https://github.com/frank-ulrich-weber/goobi-presentation/blob/reworkListView/common/class.tx_dlf_solr.php#L377)

2018-12-10 13:32 UTC, sebastian-meyer approved these changes

2018-12-10 13:34 UTC, merged