Add configuration for fields which need to be highlighted in the image
kitodo/kitodo-presentation pull request #588
Opened 2021-02-16 12:05 UTC by beatrycze-volk

This PR allows to use more than one field for highlighting words in the image. It gives also more flexibility in the name of parameters. 
Example: use 'query' param to highlight word after clicking the found result in the result list, right after chosen document is loaded it highlights word for which user was searching and then you have param 'highlight_word' which highlights word searched already inside the document itself. The first defined param on the configuration has highest priority, if not found it checks next ones. Parameters are separated by commas.

- add TypoScript configuration
- add documentation for configurable field 'searchHlElements'
- pass field value to full text control by dictionary
- use it in page view

2021-03-11 09:53 UTC, sebastian-meyer requested changes
I suggest calling the option `searchHlParameters` instead since we are dealing with URL parameters here. `elements` usually refers to HTML tags.

2021-03-11 09:53 UTC, sebastian-meyer commented on Configuration/TypoScript/Toolbox/setup.txt
> +plugin.tx_dlf_fulltexttool.searchHlElements = tx_dlf[highlight_word]
```suggestion
plugin.tx_dlf_fulltexttool.searchHlParameters = tx_dlf[highlight_word]
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Documentation/Plugins/Index.rst
> +Plugin allows also to configure (searchHlElements) by which URL parameters words will be highlighted in the image. The first defined parameter on the configuration has highest priority, if not found
```suggestion
Plugin allows also to configure (searchHlParameters) by which URL parameters words will be highlighted in the image. The first defined parameter on the configuration has highest priority, if not found it checks the next ones.
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Documentation/Plugins/Index.rst
> +       searchHlElements
```suggestion
       searchHlParameters
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Classes/Plugin/Tools/FulltextTool.php
> +            . ';search-hl-elements:' . $this->conf['searchHlElements'] . '">&nbsp;</a>';
```suggestion
            . ';search-hl-parameters:' . $this->conf['searchHlParameters'] . '">&nbsp;</a>';
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Resources/Public/Javascript/PageView/FulltextControl.js
> +            'search-hl-elements':'tx_dlf[highlight_word]'};
```suggestion
            'search-hl-parameters':'tx_dlf[highlight_word]'};
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Resources/Public/Javascript/PageView/FulltextControl.js
> +    this.searchHlElements = this.dic['search-hl-elements'];
```suggestion
    this.searchHlParameters = this.dic['search-hl-parameters'];
```

2021-03-11 09:53 UTC, sebastian-meyer commented on Resources/Public/Javascript/PageView/PageView.js
> +        this.highlightKeys = fulltextControl.searchHlElements;
```suggestion
        this.highlightKeys = fulltextControl.searchHlParameters;
```

2021-03-22 16:44 UTC, albig approved these changes
I checked again the functionality and it works with the FulltextTool as described.

A little confusing was in my setup that the word highlighting is working without the FulltextTool, too. In this case the setting of `search-hl-parameters` is fixed to `tx_dlf[highlight_word]`.

I would merge this tomorrow.

2021-03-22 22:32 UTC, sebastian-meyer approved these changes

2021-03-22 22:32 UTC, merged