Add configuration for SearchInDocument plugin
kitodo/kitodo-presentation pull request #625
Opened 2021-05-31 17:12 UTC by beatrycze-volk

Parameters have default values assigned. They are matching previous hard-coded values. Here they are only introduced, not used yet inside the code.

This PR is preparation for #587. It doesn't bring any breaking changes.

2021-06-23 10:01 UTC, beatrycze-volk commented
I'm sorry, I have deleted wrong branch and it has closed itselfafter delete.

2021-06-24 10:04 UTC, albig requested changes

2021-06-24 10:04 UTC, albig commented on Documentation/Plugins/Index.rst
> +^^^^^^^^^^^^^
```suggestion
Search in Document Tool
^^^^^^^^^^^^^^^^^^^^^^^
```
The underline of headings must be as long as the heading itself. See e.g. https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#headings

2021-06-24 10:12 UTC, albig approved these changes

2021-06-24 10:21 UTC, merged