Adjust SearchInDocument tool
kitodo/kitodo-presentation pull request #630
Opened 2021-06-24 10:51 UTC by beatrycze-volk

Use plugin configuration and adjust template. It encapsulates part of changes from the PR #587.

This PR keeps everything working. No other PRs needed to be merged before it.

Preparation for #587

2021-07-23 14:54 UTC, albig requested changes

2021-07-23 14:54 UTC, albig commented on Resources/Public/Javascript/PageView/SearchInDocument.js
> +                q: $( "input[id='tx-dlf-search-in-document-query]']" ).val(),
```suggestion
                q: $( "input[id='tx-dlf-search-in-document-query']" ).val(),
```
This doesn't work. 

I think it's a search/replace mistake.

2021-07-26 13:42 UTC, albig commented on Resources/Public/Javascript/PageView/SearchInDocument.js
> +    var currentstart = $("#tx-dlf-search-in-document-form input[id='tx-dlf-search-in-document-start]']").val();
```suggestion
    var currentstart = $("#tx-dlf-search-in-document-form input[id='tx-dlf-search-in-document-start']").val();
```
All other lines are wrong, too. This is only a sample suggest.

2021-07-26 13:42 UTC, albig requested changes
Please review all lines. Not only the one I suggest a change.

2021-07-26 15:32 UTC, beatrycze-volk commented
> Please review all lines. Not only the one I suggest a change.

Reviewed, I have changed all appearences of the error.

2021-07-27 08:59 UTC, albig approved these changes
This seems to work now. I'll merge it.

2021-07-27 08:59 UTC, merged