Move common parts of commands to own class
kitodo/kitodo-presentation pull request #634
Opened 2021-06-30 09:21 UTC by beatrycze-volk

Small quality improvements to Command classes

2021-07-19 14:28 UTC, albig requested changes
I can't get this working. Even with my two suggested changes, I run into this:

```
Uncaught TYPO3 Exception Return value of Kitodo\Dlf\Command\BaseCommand::getSolrCoreUid() must be of the type int, null returned
thrown in file /var/www/html/public/typo3conf/ext/dlf/Classes/Command/BaseCommand.php
in line 61
```

2021-07-19 14:28 UTC, albig commented on Classes/Command/IndexCommand.php
> +        $startingPoint = getStartingPoint($input->getOption('pid'));
```suggestion
        $startingPoint = $this->getStartingPoint($input->getOption('pid'));
```

2021-07-19 14:28 UTC, albig commented on Classes/Command/ReindexCommand.php
> +        $startingPoint = getStartingPoint($input->getOption('pid'));
```suggestion
        $startingPoint = $this->getStartingPoint($input->getOption('pid'));
```

2021-07-19 16:07 UTC, beatrycze-volk commented
> I can't get this working. Even with my two suggested changes, I run into this:
> 
> ```
> Uncaught TYPO3 Exception Return value of Kitodo\Dlf\Command\BaseCommand::getSolrCoreUid() must be of the type int, null returned
> thrown in file /var/www/html/public/typo3conf/ext/dlf/Classes/Command/BaseCommand.php
> in line 61
> ```

I have found a problem. I was missing _Id_ in the parameter's name for method `getSolrCoreUid`.

I have also inserted your suggestion in my fix commit.

2021-07-23 14:37 UTC, albig approved these changes
Seems to work now. Thank you.

2021-07-23 14:37 UTC, merged