Model/Repository classes
kitodo/kitodo-presentation pull request #723
Opened 2021-10-26 15:16 UTC by chrizzor

This pr adds the model/repository classes and replaces the query builder with repository calls in the merged plugins/controller.

2021-10-27 09:14 UTC, beatrycze-volk commented on Configuration/TypoScript/setup.txt
> +            Kitodo\Dlf\Domain\Model\Actionlog {
More suitable name would be ActionLog (to keep consistency with MetadataFormat and SolrCore).

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Structure.php
> +    protected $index_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Structure.php
> +    public function setIndexName(string $index_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Structure.php
> +    protected $oai_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Structure.php
> +    public function setOaiName(string $oai_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Structure.php
> +
There is no need for so many empty lines before the closing parentheses. There would be good to add one empty line after the end of the class.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/SolrCore.php
> +    protected $index_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/SolrCore.php
> +    public function setIndexName(string $index_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Printer.php
> +
There is no need for so many empty lines before the closing parentheses. There would be good to add one empty line after the end of the class.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/MetadataFormat.php
> +    protected $xpath_sorting;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/MetadataFormat.php
> +    protected $parent_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/MetadataFormat.php
> +    public function setXpathSorting(string $xpath_sorting): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/MetadataFormat.php
> +    public function setParentId(int $parent_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexAutocomplete(int $index_autocomplete): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIsListed(int $is_listed): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIsFacet(int $is_facet): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIsSortable(int $is_sortable): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexBoost(float $index_boost): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexIndexed(int $index_indexed): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexStored(int $index_stored): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexTokenized(int $index_tokenized): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setDefaultValue(string $default_value): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    public function setIndexName(string $index_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $default_value;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $sorting;
There are missing single empty lines between the properties.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_tokenized;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_stored;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_indexed;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_boost;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $is_sortable;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $is_facet;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $is_listed;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Metadata.php
> +    protected $index_autocomplete;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +
There is no need for so many empty lines before the closing parentheses. There would be good to add one empty line after the end of the class.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $index_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $oai_label;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $oai_base;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $opac_label;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $opac_base;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $union_label;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    protected $union_base;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setIndexName(string $index_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setOaiLabel(string $oai_label): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setOaiBase(string $oai_base): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setOpacLabel(string $opac_label): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setOpacBase(string $opac_base): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Library.php
> +    public function setUnionLabel(string $union_label): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setDocumentFormat(string $document_format): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setMetsOrderlabel(string $mets_orderlabel): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setMetsLabel(string $mets_label): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setOutOfPrint(string $out_of_print): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setVolumeSorting(string $volume_sorting): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setMetadataSorting(string $metadata_sorting): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setTitleSorting(string $title_sorting): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setUnionId(string $union_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setOpacId(string $opac_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setRecordId(string $record_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setProdId(string $prod_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $prod_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $record_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $opac_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $union_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $title_sorting;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $metadata_sorting;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $volume_sorting;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $out_of_print;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $rights_info;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $mets_label;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $mets_orderlabel;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    protected $document_format;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Document.php
> +    public function setRightsInfo(string $rights_info): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    protected $documents;
Collections in Document model class are defined as an ObjectStorage. Probably documents should also be defined as ObjectStorage not int, as there can be more than one document assigned to the collection.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    protected $fe_group;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    protected $index_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    protected $index_search;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    protected $oai_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    public function setIndexName(string $index_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    public function setFeGroup(string $fe_group): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    public function setIndexSearch(string $index_search): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +    public function setOaiName(string $oai_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Collection.php
> +
There is no need for so many empty lines before the closing parentheses. There would be good to add one empty line after the end of the class.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Basket.php
> +    public function setSessionId(string $session_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Basket.php
> +     * @var string|null
Default value for this property is empty string, so probably type should be only string.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    public function setCountPages(int $count_pages): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    public function setFileName(string $file_name): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    public function setUserId(int $user_id): void
The name of the parameter should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    protected $user_id;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    protected $file_name;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Domain/Model/Actionlog.php
> +    protected $count_pages;
The name of the property should be in camelCase.

2021-10-27 09:14 UTC, beatrycze-volk commented on Classes/Controller/BasketController.php
> +        $mail = $this->mailRepository->findByUid($mailId)->getFirst();
This variable is overwritten in line 546 
`$mail = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Mail\MailMessage::class);`
Therefore one of those variables should be renamed, because it is not possible to set values in line 554
`->setTo([$mail->getMail() => $mail->getName()])`

2021-10-27 09:26 UTC, beatrycze-volk commented on Classes/Controller/BasketController.php
> +            $basket = $this->basketRepository->findBasketBySessionId($sessionId)->getFirst();
Method `getFirst()` returns object or null, so check in line 213 should be against `null` not `0`.

2021-10-27 09:29 UTC, beatrycze-volk commented on Classes/Controller/BasketController.php
> -                $queryBuilder->expr()->eq('tx_dlf_mail.uid', intval($mailId)),
Method `findByUid` takes as parameter int, so it would be good not to skip` intval($mailId)`.

2021-10-27 09:43 UTC, albig requested changes
Some points have to be fixed. I'll send a PR with already done work separately.

2021-10-27 09:43 UTC, albig commented on Classes/Controller/BasketController.php
> +            $basket = $this->basketRepository->findBasketBySessionId($sessionId)->getFirst();
`findOneBySessionId()` should return only "one" and needs no extra repository method because Extbase knows what to do. (untested).

Anyway the check below is wrong.

2021-10-27 09:43 UTC, albig commented on Classes/Domain/Model/Actionlog.php
> +    protected $user_id;
Good point!

2021-11-11 15:44 UTC, albig approved these changes

2021-11-11 15:44 UTC, merged