Fix deprecation code for Typo3 v10
kitodo/kitodo-presentation pull request #744
Opened 2021-11-23 20:04 UTC by chrizzor

2021-11-25 09:09 UTC, albig requested changes
Indexing and reindexing works with my patch. See PR https://github.com/chrizzor/kitodo-presentation/pull/8.

Opening the Settings->Extension Configuration menu fails with the following message in 10.4.:

![New TYPO3 site  TYPO3 CMS 10 4 21  (1)](https://user-images.githubusercontent.com/3354500/143412141-48d81065-993f-4c66-87da-9fe028d5545b.png)

2021-11-25 10:24 UTC, chrizzor commented
The extension configuration menu shouldn't fail anymore.
It seems to me, that the manual bootstrapping is not needed in version 10.

2021-11-26 11:55 UTC, albig requested changes
![New TYPO3 site  TYPO3 CMS 10 4 21  (3)](https://user-images.githubusercontent.com/3354500/143577290-cd6d21f9-ead3-4c89-b446-7847e2f4b4db.png)

2021-11-26 15:03 UTC, albig approved these changes

2021-11-26 15:04 UTC, merged