show divs for thumbnails and descriptions only when needed and add link
kitodo/kitodo-presentation pull request #812
Opened 2022-05-11 10:59 UTC by BFallert

- only insert divs for thumbnails and description if the related fields have content.
- add a link to the collection page to the collection thumbnail image.

This eliminates the need for customization in slub_digitalcollections:
==============================================
The link to the collection thumbnail replaces a short javascript code (marked with: "// Add click event to complete collections element on intro page") in the DigitalcollectionsListScripts.js file in slub_digitalcollections.

2022-05-12 11:30 UTC, albig requested changes
Please 
* reformat the fluid tags
* make a PR afterwards to slub_digitalcollections to remove the not needed JavaScript code

2022-05-12 11:30 UTC, albig commented on Resources/Private/Templates/Collection/List.html
> +                                   pageUid="{pageUid}">
Yes, this makes sense and should work.

Could you please reformat the template tags? The source file was wrong, too. But you could fix it easily. E.g. like the following (should be examined in an IDE/Editor):
```suggestion
                <f:if condition="{item.collection.thumbnail}">
                    <div class="tx-dlf-collection-thumbnail">
                        <f:link.action action="show"
                                       arguments="{collection : item.collection}"
                                       pageUid="{pageUid}">
```

2022-05-13 07:13 UTC, albig approved these changes

2022-05-13 07:14 UTC, merged

2022-05-13 08:06 UTC, BFallert commented
Done: make a PR afterwards to slub_digitalcollections to remove the not needed JavaScript code