Multidomain typoscript configuration bugfix
kitodo/kitodo-presentation pull request #845
Opened 2022-08-04 06:33 UTC by chrizzor

Read the typoscript configuration depending on the page where it is placed on.
Otherwise, multi domain installation only get the default site root typoscript.
This PR is linked to issue #841

2022-08-04 16:14 UTC, sebastian-meyer requested changes

2022-08-04 16:14 UTC, sebastian-meyer commented on Classes/Hooks/ItemsProcFunc.php
> +        $this->storagePid = $typoscriptConfig["plugin."]["tx_dlf."]["persistence."]["storagePid"];
```suggestion
        $this->storagePid = $typoscriptConfig['plugin.']['tx_dlf.']['persistence.']['storagePid'];
```

2022-08-04 16:14 UTC, sebastian-meyer commented on Classes/Hooks/ItemsProcFunc.php
> +            die($e->getMessage());
Please use proper error handling here instead of just exiting the script.

2022-08-05 08:03 UTC, chrizzor commented
Requested changes should be fixed now

2022-08-05 11:34 UTC, sebastian-meyer requested changes
Please check the codacy issues. Apart from that, everything looks good, now!

2022-08-05 11:57 UTC, sebastian-meyer submitted a review, later dismissed
Perfect! I can merge this as soon as you bring your branch up to date with the base branch.

(When opening a pull request you can choose to allow me to commit changes to your branch. If you do so, I can update your branch myself.)

2022-08-08 07:54 UTC, sebastian-meyer approved these changes

2022-08-08 07:54 UTC, merged