[BUGFIX] Fix virtual and normal collections
kitodo/kitodo-presentation pull request #874
Opened 2022-12-06 09:24 UTC by michaelkubina

This PR fixes a variety of issues with collections:
- the collection parameter (context) does not get lost, when using facets or the sorting form
- collections are now unified in the collection parameter instead of two separate ones (= single collection and list of collections)
- list of collections in the search-plugin (settings.collections) are working now
- the facet count now works properly when entering a collection or browsing a list of collections
- virtual collections are working now and the solr-queries get applied on the actual search
- combinations of normal and virtual collections can be intertwined and will be queried and displayed correctly

2022-12-06 09:40 UTC, michaelkubina commented
Fix for virtual collection issues https://github.com/kitodo/kitodo-presentation/issues/866 and https://github.com/kitodo/kitodo-presentation/issues/641

For the latter its the missing implementation as well.

2023-01-30 07:57 UTC, sebastian-meyer requested changes

2023-01-30 07:57 UTC, sebastian-meyer commented on Classes/Common/SolrSearch.php
> +                else {
```suggestion
                } else {
```

2023-01-30 07:57 UTC, sebastian-meyer commented on Classes/Common/SolrSearch.php
> +            $params['filterquery'][]['query'] = implode(" OR ", array_filter([$collectionsQueryString, $virtualCollectionsQueryString]));
```suggestion
            $params['filterquery'][]['query'] = implode(' OR ', array_filter([$collectionsQueryString, $virtualCollectionsQueryString]));
```

2023-01-30 08:06 UTC, sebastian-meyer requested changes
This looks fine apart from the tests not running through. Please have a look at this!

2023-01-31 12:17 UTC, michaelkubina commented
I can see the issue, but i am not sure wether i'm allowed to fix it in the testrun itself or if this has to stay unchanged and i must apply a fix to the `findSolrByCollection()` function.

Explanation: The expected type for the collection argument in `findSolrByCollection()` has changed...before it could have been either a string or an array. `solrSearch.php` has then decided how to build the query, depending on if its just a single collection or a list of collections (the latter did not work iirc). This has been now harmonised so that an array is always the expected argument.

The reason behind it is, that the `search-parameter` does not differentiate between a single collection (when coming from the collection-controller and others) or a list of collections (only when coming from the search-plugin/listview) anymore. Both use the same collection-parameter now (instead of the 2 seperate ones before) and either provides a single UID or a comma separated list of UIDs. This gets exploded, so we can loop through the array, and we obtain the collections from those UIDs and save them as a new array. The query building mechanism in the `SolrSearch.php`, that comes next, now does not need to check wether it got a string or array anymore, but can simply loop through it...which helps readabilty and made the integration of virtual collections queries easier.

Internally all calls to `findSolrByCollection` now (since this PR) pass collections as arrays, except for the testrun which i did not know of.

So, without being able to test it, i think just a small change in the `canSearchInCollection()` function is required - at least i hope so. Like:

```
$musik = array($collections[0]);
$dresdnerHefte = array($collections[1]);
```

Some feedback would be appreciated, because i dont want to mess with the unit test itself.

2023-02-01 14:15 UTC, sebastian-meyer commented
> I can see the issue, but i am not sure wether i'm allowed to fix it in the testrun itself or if this has to stay unchanged and i must apply a fix to the `findSolrByCollection()` function.

Since you changed how collections are handled, you need to update the test accordingly.

2023-02-02 11:46 UTC, sebastian-meyer approved these changes
Thank you very much!

2023-02-02 11:46 UTC, merged