Added format unit tests.
kitodo/kitodo-presentation pull request #894
Opened 2023-01-30 09:43 UTC by haogatyp

Some of the tests fail because the existing code being tested appears to be buggy.

2023-02-01 17:00 UTC, sebastian-meyer commented
Could you please bring this pull request up to date with master? Alternatively you can allow me to update your branch, then I can do it myself via GitHub most of the time.

2023-02-06 17:00 UTC, haogatyp commented
> Could you please bring this pull request up to date with master? Alternatively you can allow me to update your branch, then I can do it myself via GitHub most of the time.

I did a rebase onto current master.

2023-09-27 10:39 UTC, sebastian-meyer commented
@haogatyp Please bring your branch up-to-date with the master branch.

2023-10-25 15:58 UTC, oliver-stoehr commented
@sebastian-meyer the pull request is fixed and updated

2023-10-25 16:05 UTC, sebastian-meyer commented
Please have a look at the issues reported by Codacy: https://github.com/kitodo/kitodo-presentation/runs/18049153004

2023-10-26 05:27 UTC, sebastian-meyer commented
Thank you, but there is still one last issue remaining... ;o)

2023-10-26 05:34 UTC, sebastian-meyer requested changes
Please fix the filename (see comment) and add the default license header to every PHP file. Just copy and paste from any other code file!

After that we are finally ready for merging!

2023-10-26 05:34 UTC, sebastian-meyer commented on Tests/Fixtures/Format/modsOriginInfoWithEditionElectonicEd.xml
> +<?xml version="1.0" encoding="UTF-8"?>
There is a typo in the file name.

2023-10-26 06:01 UTC, sebastian-meyer approved these changes
Thank you so much!

2023-10-26 06:01 UTC, merged