[MAINTENANCE] Add fallback option for getLLL()
kitodo/kitodo-presentation pull request #917
Opened 2023-02-24 13:16 UTC by csidirop

This PR implements a fallback option in getLLL() if there is no translation for given key as proposed in https://github.com/kitodo/kitodo-presentation/issues/916

2023-02-24 13:24 UTC, csidirop commented
Updated commit to meet Codacy Productions static code analysis requirements

2023-03-09 17:08 UTC, sebastian-meyer requested changes

2023-03-09 17:08 UTC, sebastian-meyer commented on Classes/Controller/Backend/NewTenantController.php
> +        } else if (isset($langArray['default'][$index][0]['target'])) {
```suggestion
        } elseif (isset($langArray['default'][$index][0]['target'])) {
```

2023-03-09 17:08 UTC, sebastian-meyer commented on Classes/Controller/Backend/NewTenantController.php
> +            return "Missing translation for ".substr($index, 9); //cut 'metadata.' string
Since this method is not only used for metadata, but also for structure labels, the `substr()` function would not work as intended. I'd be fine with just using the whole translation key here:
```suggestion
            return 'Missing translation for ' . $index;
```
What do you think?

2023-03-10 08:06 UTC, csidirop commented on Classes/Controller/Backend/NewTenantController.php
> +            return "Missing translation for ".substr($index, 9); //cut 'metadata.' string
Ok I didn't knew that. Your suggestion looks fine to me.

2023-03-10 08:10 UTC, sebastian-meyer approved these changes
Thank you!

2023-03-10 08:57 UTC, merged