Complete tests for MetsDocument
kitodo/kitodo-presentation pull request #919
Opened 2023-02-27 11:06 UTC by oliver-stoehr

2023-10-26 15:22 UTC, sebastian-meyer requested changes

2023-10-26 15:22 UTC, sebastian-meyer commented on Tests/Fixtures/MetsDocument/mets_with_pages.xml
> +                <mets:FLocat LOCTYPE="URL" xlink:href="fulltext_0001.xml"/>
Is it intentional that this (and `FULLTEXT_0002` and `FULLTEXT_0004`) is not a valid URL? Looks like only the entry for `FULLTEXT_0003` is used in the tests which also is the only one with a valid URL.

If we do not need invalid METS for testing, we should fix this and use valid URLs for every FULLTEXT entry.

2023-10-27 07:59 UTC, oliver-stoehr commented
@sebastian-meyer I fixed the URLs

2023-10-27 09:10 UTC, sebastian-meyer approved these changes
Thank you!

2023-10-27 09:10 UTC, merged