Add tests for Common package
kitodo/kitodo-presentation pull request #953
Opened 2023-04-28 16:12 UTC by oliver-stoehr

2023-11-29 14:57 UTC, sebastian-meyer requested changes

2023-11-29 14:57 UTC, sebastian-meyer commented on Tests/Fixtures/Common/solrcores.xml
This file is superseded by `Tests/Fixtures/Common/solrcores.csv`, isn't it? Then it should be removed from the PR.

2023-11-29 15:00 UTC, sebastian-meyer requested changes

2023-11-29 15:00 UTC, sebastian-meyer commented on Tests/Functional/Common/SolrSearchTest.php
> +        $this->markTestSkipped('Does not work in combination with other tests.');
Hm, a skipped test is quite useless... There should be a way to make this work even in combination with the other tests. Where exactly does the test fail?

2023-11-30 11:31 UTC, oliver-stoehr commented on Tests/Fixtures/Common/solrcores.xml
Thank you for pointing out, I removed this file.

2023-11-30 11:39 UTC, oliver-stoehr commented on Tests/Functional/Common/SolrSearchTest.php
> +        $this->markTestSkipped('Does not work in combination with other tests.');
I reenabled the test. It fails on line 55 at the first `assert` using the `SolrSearch` object from line 53. I could not find any difference in any variables accesses in the tested `SolrSearch::prepare` method.
I also switched to a different Solr core, but that didn't change the result.
However I'm not sure about the `DocumentRepository` passed to the constructor of the `SolrSearch` – I'm don't fully understand how the `DocumentRepository` object is created (or maybe reused?).

2023-12-01 18:10 UTC, sebastian-meyer commented
I fixed the PHPStan issue in `master`. It should disappear as soon as you update your branch.

2023-12-01 18:13 UTC, sebastian-meyer commented on Tests/Functional/Common/SolrSearchTest.php
> +        $this->markTestSkipped('Does not work in combination with other tests.');
I am sorry, but I can't help you with that. Maybe @beatrycze-volk can give more insight into using the `DocumentRepository` correctly?

2023-12-04 09:43 UTC, beatrycze-volk commented on Tests/Functional/Common/SolrSearchTest.php
> +        $this->markTestSkipped('Does not work in combination with other tests.');
> I am sorry, but I can't help you with that. Maybe @beatrycze-volk can give more insight into using the `DocumentRepository` correctly?

Actually more suitable person to answer this question would be @chrizzor as he has implemented this class.

2023-12-04 17:33 UTC, oliver-stoehr commented
I fixed the test. It looks like some database query were cached, that were necessary to determine the correct solr core. The solr cores are now determined more directly.

2023-12-04 21:18 UTC, sebastian-meyer approved these changes
Great job! Thank you very much!

2023-12-04 21:19 UTC, sebastian-meyer commented
Now you only need to update your branch to master and then I can merge it!

2023-12-05 10:49 UTC, merged